package com.Clubbr.Clubbr.utils;

public enum permission {
    READ_STABLISHMENTS,
    READ_MANAGER_STABLISHMENTS,
    CREATE_STABLISHMENTS,
    CREATE_WORKERS,
    UPDATE_WORKERS,
    CREATE_MANAGERS,
    READ_EVENTS,
    CREATE_EVENTS,
    READ_INTEREST_POINTS,
    CREATE_INTEREST_POINTS,
    READ_TICKETS,
    CREATE_TICKETS,
    READ_USERS,
    UPDATE_USERS,
    DELETE_USERS,
    UPDATE_STABLISHMENTS,
    DELETE_STABLISHMENTS,
    UPDATE_EVENTS,
    DELETE_EVENTS,
    UPDATE_INTEREST_POINTS,
    DELETE_INTEREST_POINTS
}
